language: java
jdk:
- oraclejdk8
services:
- docker

install:
- mvn clean install

script:
- docker login -u ${hubaccount} -p ${hubpwd}

- docker build -t yokv/sc-devops-eureka ./eureka
- docker push yokv/sc-devops-eureka
- docker build -t yokv/sc-devops-app-a ./app-a
- docker push yokv/sc-devops-app-a
- docker build -t yokv/sc-devops-app-b ./app-b
- docker push yokv/sc-devops-app-b

branches:
  only:
  - master
notifications:
  webhooks: https://oapi.dingtalk.com/robot/send?access_token=aee16a814aa2d5b289cf6453ba8ee2144b477e2fd5a759ceee777b826494d842
  slack:
    on_success: never
    on_failure: never
    
