language: java
jdk:
- oraclejdk8
services:
- docker

script:
- mvn clean package docker:build

branches:
  only:
  - master
notifications:
  webhooks: https://oapi.dingtalk.com/robot/send?access_token=aee16a814aa2d5b289cf6453ba8ee2144b477e2fd5a759ceee777b826494d842
  slack:
    on_success: never
    on_failure: never

