version: "3"
services:
  eureka:
    image: yokv/sc-devops-eureka
    ports:
    - 8761:8761
    networks:
    - cloud-net
    environment:
      SPRING_PROFILES_ACTIVE: stack
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '2'
          memory: 2048M
        reservations:
          cpus: '0.50'
          memory: 512M

  app-a:
    image: yokv/sc-devops-app-a
    networks:
    - cloud-net
    environment:
      SPRING_PROFILES_ACTIVE: stack
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '2'
          memory: 2048M
        reservations:
          cpus: '0.50'
          memory: 512M

  app-b:
    image: yokv/sc-devops-app-b
    networks:
    - cloud-net
    environment:
      SPRING_PROFILES_ACTIVE: stack
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '2'
          memory: 2048M
        reservations:
          cpus: '0.50'
          memory: 512M

networks:
  cloud-net:
    external:
      name: cloud-net