version: "3"
services:
  eureka:
    image: yokv/eureka
    ports:
    - 8761:8761
    networks:
    - app-net

  app-a:
    image: yokv/app-a
    networks:
    - app-net
    expose:
    - 8080
    environment:
      SPRING_PROFILES_ACTIVE: compose

  app-b:
    image: yokv/app-b
    networks:
    - app-net
    expose:
    - 8088
    environment:
      SPRING_PROFILES_ACTIVE: compose

networks:
  app-net:
