version: "3"
services:
  eureka:
    build: ./eureka
    image: yokv/sc-devops-eureka
    ports:
    - 8761:8761
    networks:
    - app-net

  app-a:
    build: ./app-a
    image: yokv/sc-devops-app-a
    networks:
    - app-net
    expose:
    - 8080
    environment:
      SPRING_PROFILES_ACTIVE: compose

  app-b:
    build: ./app-b
    image: yokv/sc-devops-app-b
    networks:
    - app-net
    expose:
    - 8088
    environment:
      SPRING_PROFILES_ACTIVE: compose

networks:
  app-net:
