eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 80
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: app-a
        uri: lb://app-a
        predicates:
        - Path=/a/**
      - id: app-b
        uri: lb://app-b
        predicates:
        - Path=/b/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true