apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  selector:
    matchLabels:
      app: eureka
      role: peer1
      tier: server
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka
        role: peer1
        tier: server
    spec:
      containers:
      - name: master
        image: yokv/eureka
        resources:
          requests:
            cpu: 1000m
            memory: 1000Mi
        ports:
        - containerPort: 8761

---

apiVersion: v1
kind: Service
metadata:
  name: eureka
  labels:
    app: eureka
    role: peer1
    tier: server
spec:
  ports:
  - port: 8761
    targetPort: 8761
  selector:
    app: eureka
    role: peer1
    tier: server