spring:
  application:
    name: eureka
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    response-cache-update-interval-ms: 1000
    response-cache-auto-expiration-in-seconds: 180
    eviction-interval-timer-in-ms: 5000 # 清理间隔 默认1分钟
    renewal-threshold-update-interval-ms: 75000 # 续约的阈值
  instance:
    lease-expiration-duration-in-seconds: 15 # eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance
    lease-renewal-interval-in-seconds: 5 # eureka client发送心跳给server端的频率