eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
spring:
  cloud:
    inetutils:
      preferred-networks: 10.0.1.