apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a
  labels:
    app: app-a
    tier: backend
spec:
  selector:
    matchLabels:
      app: app-a
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: app-a
        tier: backend
    spec:
      containers:
      - name: app-a
        image: yokv/app-a
        ports:
        - containerPort: 8080
        env:
        - name: eureka.client.registry-fetch-interval-seconds
          value: "5"
        - name: eureka.client.serviceUrl.defaultZone
          value: http://eureka:8761/eureka/
