apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
    tier: backend
spec:
  selector:
    matchLabels:
      app: gateway
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
        tier: backend
    spec:
      containers:
      - name: gateway
        image: yokv/gateway
        resources:
          requests:
            cpu: 1000m
            memory: 1000Mi
        ports:
        - containerPort: 80
        env:
        - name: eureka.client.registry-fetch-interval-seconds
          value: "5"
        - name: eureka.client.serviceUrl.defaultZone
          value: http://eureka:8761/eureka/
---

apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: gateway
    tier: backend