version: "3"
services:
  eureka:
    image: yokv/eureka
    ports:
    - 8761:8761
    networks:
    - app-net

  app-a:
    image: yokv/app-a
    networks:
    - app-net
    expose:
    - 8080
    environment:
    - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    - eureka.client.registry-fetch-interval-seconds=5
    - eureka.instance.prefer-ip-address=true

  app-b:
    image: yokv/app-b
    networks:
    - app-net
    expose:
    - 8088
    environment:
    - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    - eureka.client.registry-fetch-interval-seconds=5
    - eureka.instance.prefer-ip-address=true

  gateway:
    image: yokv/gateway
    networks:
    - app-net
    ports:
    - 80:80
    environment:
    - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    - eureka.client.registry-fetch-interval-seconds=5
    - eureka.instance.prefer-ip-address=true

networks:
  app-net:
