version: "3"
services:
  eureka:
    image: yokv/eureka
    ports:
    - 8761:8761
    networks:
    - cloud-net
    environment:
    - spring.cloud.inetutils.preferred-networks=10.0.1.
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '2'
          memory: 2048M
        reservations:
          cpus: '0.50'
          memory: 512M

  app-a:
    image: yokv/app-a
    networks:
    - cloud-net
    environment:
    - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    - eureka.client.registry-fetch-interval-seconds=5
    - eureka.instance.prefer-ip-address=true
    - spring.cloud.inetutils.preferred-networks=10.0.1.
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '2'
          memory: 2048M
        reservations:
          cpus: '0.50'
          memory: 512M

  app-b:
    image: yokv/app-b
    networks:
    - cloud-net
    environment:
    - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    - eureka.client.registry-fetch-interval-seconds=5
    - eureka.instance.prefer-ip-address=true
    - spring.cloud.inetutils.preferred-networks=10.0.1.
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '2'
          memory: 2048M
        reservations:
          cpus: '0.50'
          memory: 512M


  gateway:
    image: yokv/gateway
    networks:
    - cloud-net
    environment:
    - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    - eureka.client.registry-fetch-interval-seconds=5
    - eureka.instance.prefer-ip-address=true
    - spring.cloud.inetutils.preferred-networks=10.0.1.
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '2'
          memory: 2048M
        reservations:
          cpus: '0.50'
          memory: 512M

networks:
  cloud-net:
    external:
      name: cloud-net